version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: go-project-db-1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./start.sql:/docker-entrypoint-initdb.d/start.sql
    
    extra_hosts:
      - "host.docker.internal:host-gateway"

  app:
    build: .
    container_name: go-project-app-1
    restart: always
    environment:
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: "host.docker.internal"
      DATABASE_PORT: ${DATABASE_PORT}
      SESSION_SECRET: ${SESSION_SECRET}
    ports:
      - "8001:8001"
    depends_on:
      - db
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  db_data:
